### ISSUE TITLE
大佬，本人引入到项目，报错

### ISSUE THREAD

**Issue by zhou1992zg** [yezihaohao/react-qmap#1]
最近的小程序这样报错
<img width="633" alt="2018-09-20 8 20 44" src="https://user-images.githubusercontent.com/29066081/45832599-f0c21380-bd34-11e8-86f0-3b3d30783682.png">
H5端这样报错
<img width="686" alt="2018-09-21 12 26 54" src="https://user-images.githubusercontent.com/29066081/45832668-26ff9300-bd35-11e8-8e31-72997b06d46e.png">

**Comment by zhou1992zg** [comment]
> 最近的小程序这样报错
> 


> H5端这样报错
> <img alt="2018-09-21 12 26 54" width="686" src="https://user-images.githubusercontent.com/29066081/45832668-26ff9300-bd35-11e8-8e31-72997b06d46e.png">

**Comment by yezihaohao** [comment]
[https://github.com/yezihaohao/react-qmap#taro](https://github.com/yezihaohao/react-qmap#taro)
