### ISSUE TITLE
有多边形绘制工具吗

### ISSUE THREAD

**Issue by 986244073** [yezihaohao/react-qmap#16]
有多边形绘制工具吗
    const drawingManager = new window.qq.maps.drawing.DrawingManager({
      drawingMode: window.qq.maps.drawing.OverlayType.MARKER,
      drawingControl: true,
      drawingControlOptions: {
        position: window.qq.maps.ControlPosition.TOP_CENTER,
        drawingModes: [
          window.qq.maps.drawing.OverlayType.MARKER,
          window.qq.maps.drawing.OverlayType.CIRCLE,
          window.qq.maps.drawing.OverlayType.POLYGON,
          window.qq.maps.drawing.OverlayType.POLYLINE,
          window.qq.maps.drawing.OverlayType.RECTANGLE,
        ],
      },
      circleOptions: {
        fillColor: new window.qq.maps.Color(255, 208, 70, 0.3),
        strokeColor: new window.qq.maps.Color(88, 88, 88, 1),
        strokeWeight: 3,
        clickable: false,
      },
    });
    drawingManager.setMap(map);
报错

**Comment by yezihaohao** [comment]
最新版已支持，[示例](https://react-qmap-8meha15de.vercel.app/#/drawing)
