### ISSUE TITLE
反地址解析求粟子

### ISSUE THREAD

**Issue by lxf520wan** [yezihaohao/react-qmap#2]
Home.js:270 Uncaught TypeError: geocoder.getAddress is not a function  一直报错,找不到方法.
_getMap = (map, wMap) => {
        classMap = map;
        windowMap = wMap;
        geocoder = wMap.Geocoder;
        geocoder.getAddress(map.getCenter());

**Comment by raintao** [comment]
getMap = (map, wMap) => {
    windowMap = wMap;
    classMap = map;
    windowMap.event.addListener(classMap, 'click', event => {
      this.handleMapClick(event.latLng.getLat(), event.latLng.getLng());
    })
}

handleMapClick = (lat, lng) => {
    const geocoder = new windowMap.Geocoder();
    geocoder.getAddress(new windowMap.LatLng(lat, lng));
    geocoder.setComplete(res => {
      const addComp = res.detail.addressComponents;
    });
    geocoder.setError(res => {
      // eslint-disable-next-line no-console
      console.log(res);
      message.error('定位解析失败，请稍后再试！');
    });
};

**Comment by yezihaohao** [comment]
https://codesandbox.io/s/cool-hopper-49nf0?file=/src/App.js
