### ISSUE TITLE
关于获取当前位置的经纬度的问题？

### ISSUE THREAD

**Issue by raintao** [yezihaohao/react-qmap#6]
拿到windowMap后
1. 本来是想用腾讯的Geolocation获取当前位置的经纬度，但是new windowMap.Geolocation时没有Geolocation构造函数
2. 用浏览器H5的navigator定位，经常定位异常
3. 先用百度地图定位，在转为腾讯地图经纬度，但是windowMap.convertor.translate报错，没有convertor
希望作者能看帮忙看下这些常用的api都没法用

**Comment by hufans** [comment]
> 拿到windowMap后
> 
> 1. 本来是想用腾讯的Geolocation获取当前位置的经纬度，但是new windowMap.Geolocation时没有Geolocation构造函数
> 2. 用浏览器H5的navigator定位，经常定位异常
> 3. 先用百度地图定位，在转为腾讯地图经纬度，但是windowMap.convertor.translate报错，没有convertor
>    希望作者能看帮忙看下这些常用的api都没法用
html 5 geolocation.getCurrentLocation()

**Comment by yezihaohao** [comment]
convertor需要加libraries，具体用法参考readme libraries用法和示例
